In [1]:
import pandas as pd

# Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [62]:
csv_data = r'c:\Users\petrenkovn\Dropbox\DS-22\Data_Files\ml-latest-small\ratings.csv'

dataset = pd.read_csv( csv_data )

# Определить, какому фильму было выставлено больше всего оценок 5.0.
f"movieId={list(dict(dataset[ dataset['rating']==5.0 ]['movieId'].value_counts()).keys())[0]}"

'movieId=318'

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [83]:
csv_data = r'c:\Users\petrenkovn\Dropbox\DS-22\Data_Files\power.csv'

dataset = pd.read_csv( csv_data )

# список стран, упорядоченный по алфавиту, чтобы скопировать нужные значения
# dataset.sort_values(by='country')['country'].unique()

# Посчитать суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.
dataset[ ( dataset['country'].isin(['Latvia','Lithuania','Estonia']) ) & ( dataset['category'].isin([4,12,21]) ) & ( dataset['year'] >= 2005 ) & ( dataset['year'] <= 2010 ) &  ( dataset['quantity'] > 0 ) ]['quantity'].sum()

240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.

In [90]:
webpage_with_tabledata = 'https://www.cbr.ru/currency_base/daily/'

# Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
pd.read_html( webpage_with_tabledata )[0]

,Цифр. код,Букв. код,Единиц,Валюта,Курс
0,36,AUD,1,Австралийский доллар,550955
1,944,AZN,1,Азербайджанский манат,430368
2,51,AMD,100,Армянских драмов,142131
3,933,BYN,1,Белорусский рубль,288303
4,975,BGN,1,Болгарский лев,453089
5,986,BRL,1,Бразильский реал,145485
6,348,HUF,100,Венгерских форинтов,249542
7,410,KRW,1000,Вон Республики Корея,669853
8,344,HKD,10,Гонконгских долларов,943271
9,208,DKK,1,Датская крона,119062
10,840,USD,1,Доллар США,731195
11,978,EUR,1,Евро,887744
12,356,INR,100,Индийских рупий,992097
13,398,KZT,100,Казахстанских тенге,174472
14,124,CAD,1,Канадский доллар,573172
15,417,KGS,100,Киргизских сомов,861982
16,156,CNY,1,Китайский юань,111778
17,498,MDL,10,Молдавских леев,424496
18,934,TMT,1,Новый туркменский манат,209212
19,578,NOK,10,Норвежских крон,831773
20,985,PLN,1,Польский злотый,199546
21,946,RON,1,Румынский лей,182012
22,960,XDR,1,СДР (специальные права заимствования),1048153
23,702,SGD,1,Сингапурский доллар,547097
24,972,TJS,10,Таджикских сомони,645504
25,949,TRY,10,Турецких лир,918298
26,860,UZS,10000,Узбекских сумов,700172
27,980,UAH,10,Украинских гривен,261535
28,826,GBP,1,Фунт стерлингов Соединенного королевства,967371
29,203,CZK,10,Чешских крон,336089
30,752,SEK,10,Шведских крон,863909
31,756,CHF,1,Швейцарский франк,824067
32,710,ZAR,10,Южноафриканских рэндов,482917
33,392,JPY,100,Японских иен,702296